name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cilium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: |
          # Install clang & libbpf
          sudo apt update -y
          sudo apt install -y clang-12
          mkdir -p /usr/include/bpf/
          curl -sSL "https://github.com/libbpf/libbpf/archive/refs/tags/v0.5.0.tar.gz" -o /tmp/libbpf.tar.gz
          tar -xvf /tmp/libbpf.tar.gz --strip-components=2 -C /usr/include/bpf "libbpf-0.5.0/src/bpf_helper_defs.h" "libbpf-0.5.0/src/bpf_helpers.h"
      - working-directory: cilium
        run: go generate
