name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["cilium"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: ls -al /sys/kernel/btf && ls -al
      - run: |
          # Generate BTF headers
          ls -al /sys/kernel/btf && ls -al
          bpftool btf dump file /sys/kernel/btf/vmlinux format c > ./bpf/headers/vmlinux.h
      - working-directory: ${{ matrix.dir }}
        run: go generate
