name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cilium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - run: |
          # Install libbpf
          sudo apt update -y
          sudo apt install -y libbpf
      - working-directory: cilium
        run: go generate
